general {
    col.active_border = rgba(C62828FF) rgba(C2185BFF) 45deg
    col.inactive_border = rgba(E0D8D0FF)
}

decoration {
    shadow {
        color = rgba(2D2B2822)
    }
}

group {
    col.border_active = rgba(C62828FF) rgba(C2185BFF) 45deg
    col.border_inactive = rgba(E0D8D0FF)

    groupbar {
        col.active = rgba(C62828FF)
        col.inactive = rgba(F0EDE8FF)
        text_color = rgba(2D2B28FF)
    }
}
